name: "Build and Publish Docker Images"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  DOCKER_ORGANIZATION: ftheirs

jobs:
  build_docker_images:
    runs-on: self-hosted
    strategy:
      matrix:
        image: ["anvil", "bootstrapper", "madara", "orchestrator", "pathfinder"]
      # Set fail-fast to false to prevent cancellation of other jobs
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Git commit hash
        id: hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: deps/${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_ORGANIZATION }}/${{ matrix.image }}:latest
            ${{ env.DOCKER_ORGANIZATION }}/${{ matrix.image }}:${{ github.event.inputs.version }}-${{ steps.hash.outputs.hash }}
        # Continue on error to allow other jobs to complete
        continue-on-error: false